language: node_js
node_js:
  - 4
  - 5
  - 6
sudo: false
before_script:
  - git config --global user.email "dev@carrotcreative.com"
  - git config --global user.name "Carrot Creative"
after_script:
  - npm run coveralls
